/**
 * Seed workouts — see ../seedDatabase.ts for how these are written, and
 * ./types.ts for what an entry in `exercises` means.
 *
 * Grew from 2 to 17 and then to 42 on 4 Sep 2026. Every one of the 15
 * fitness/combined programs is now navigable end to end — Program Detail into
 * Workout Detail into Active Workout — instead of only the first one.
 *
 * The three `nutrition` programs deliberately have no workouts at all. Their
 * content is the recipes; inventing a token training day for them would be
 * fake, and Program Detail already renders an empty workout list correctly.
 *
 * Programming conventions used throughout, so the data reads as a real plan
 * rather than a random list of movements:
 * - every session opens with a `warmup` and closes with a `cooldown`;
 * - set/rep schemes track the program's intent (5 x 5 and 4 x 6 for the
 *   powerlifting and strength programs, 3-4 x 10-12 for hypertrophy,
 *   4 x 15-20 for the conditioning circuits, 2-3 x 1 holds for mobility);
 * - a workout stays inside the equipment its program promises — Home
 *   Bodyweight Blast and Desk Reset use nothing, Kettlebell Conditioning
 *   uses a kettlebell, and so on.
 */
import type { SeedWorkout } from "./types";

export const seedWorkouts: SeedWorkout[] = [
  // ---- Full Body Foundations (free, 4 weeks) -----------------------------
  {
    id: "wk-fbf-day1",
    programId: "prog-full-body-beginner",
    name: "Day 1: Full Body A",
    order: 1,
    durationMinutes: 30,
    intensity: "beginner",
    exercises: [
      ["ex-jog", "warmup", 1, 1],
      ["ex-squat", "main", 3, 12],
      ["ex-pushup", "main", 3, 10],
      ["ex-plank", "main", 3, 1],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-fbf-day2",
    programId: "prog-full-body-beginner",
    name: "Day 2: Full Body B",
    order: 2,
    durationMinutes: 35,
    intensity: "beginner",
    exercises: [
      ["ex-jog", "warmup", 1, 1],
      ["ex-deadlift", "main", 3, 8],
      ["ex-pullup", "main", 3, 5],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-fbf-day3",
    programId: "prog-full-body-beginner",
    name: "Day 3: Full Body C",
    order: 3,
    durationMinutes: 35,
    intensity: "beginner",
    exercises: [
      ["ex-jog", "warmup", 1, 1],
      ["ex-walking-lunge", "main", 3, 10],
      ["ex-bench-press", "main", 3, 10],
      ["ex-dead-bug", "main", 3, 8],
      ["ex-hamstring-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- Home Bodyweight Blast (free, 4 weeks, no equipment) ---------------
  {
    id: "wk-hbw-a",
    programId: "prog-home-bodyweight",
    name: "Home Day 1",
    order: 1,
    durationMinutes: 25,
    intensity: "beginner",
    exercises: [
      ["ex-jog", "warmup", 1, 1],
      ["ex-squat", "main", 3, 15],
      ["ex-pushup", "main", 3, 10],
      ["ex-walking-lunge", "main", 3, 12],
      ["ex-plank", "main", 3, 1],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-hbw-b",
    programId: "prog-home-bodyweight",
    name: "Home Day 2",
    order: 2,
    durationMinutes: 25,
    intensity: "beginner",
    exercises: [
      ["ex-mountain-climber", "warmup", 1, 1],
      ["ex-jump-squat", "main", 3, 12],
      ["ex-bench-dip", "main", 3, 10],
      ["ex-side-plank", "main", 3, 1],
      ["ex-crunch", "main", 3, 20],
      ["ex-childs-pose", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-hbw-c",
    programId: "prog-home-bodyweight",
    name: "Home Day 3",
    order: 3,
    durationMinutes: 30,
    intensity: "intermediate",
    exercises: [
      ["ex-inchworm", "warmup", 1, 1],
      ["ex-push-ups-with-feet-elevated", "main", 3, 10],
      ["ex-glute-bridge", "main", 3, 12],
      ["ex-reverse-crunch", "main", 3, 15],
      ["ex-superman", "main", 3, 12],
      ["ex-worlds-greatest-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- Mobility & Recovery (free, 3 weeks) -------------------------------
  {
    id: "wk-mob-a",
    programId: "prog-mobility-recovery",
    name: "Session A: Spine & Hips",
    order: 1,
    durationMinutes: 20,
    intensity: "beginner",
    exercises: [
      ["ex-cat-stretch", "warmup", 1, 1],
      ["ex-childs-pose", "main", 3, 1],
      ["ex-hamstring-stretch", "main", 3, 1],
      ["ex-superman", "main", 3, 10],
      ["ex-dead-bug", "main", 3, 8],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-mob-b",
    programId: "prog-mobility-recovery",
    name: "Session B: Full Body Reset",
    order: 2,
    durationMinutes: 20,
    intensity: "beginner",
    exercises: [
      ["ex-inchworm", "warmup", 1, 1],
      ["ex-glute-bridge", "main", 3, 10],
      ["ex-side-plank", "main", 3, 1],
      ["ex-childs-pose", "main", 3, 1],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-mob-c",
    programId: "prog-mobility-recovery",
    name: "Session C: Legs & Groin",
    order: 3,
    durationMinutes: 20,
    intensity: "beginner",
    exercises: [
      ["ex-arm-circles", "warmup", 1, 1],
      ["ex-worlds-greatest-stretch", "main", 3, 1],
      ["ex-runners-stretch", "main", 3, 1],
      ["ex-side-lying-groin-stretch", "main", 3, 1],
      ["ex-standing-gastrocnemius-calf-stretch", "main", 3, 1],
      ["ex-childs-pose", "cooldown", 1, 1],
    ],
  },

  // ---- Active Aging (free, 6 weeks, low impact) --------------------------
  {
    id: "wk-aa-a",
    programId: "prog-active-aging",
    name: "Week A: Strength & Balance",
    order: 1,
    durationMinutes: 25,
    intensity: "beginner",
    exercises: [
      ["ex-arm-circles", "warmup", 1, 1],
      ["ex-chair-squat", "main", 3, 10],
      ["ex-band-pull-apart", "main", 3, 12],
      ["ex-glute-bridge", "main", 3, 10],
      ["ex-standing-dumbbell-calf-raise", "main", 3, 12],
      ["ex-cat-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-aa-b",
    programId: "prog-active-aging",
    name: "Week A: Low-Impact Cardio",
    order: 2,
    durationMinutes: 30,
    intensity: "beginner",
    exercises: [
      ["ex-arm-circles", "warmup", 1, 1],
      ["ex-stationary-bike", "main", 1, 1],
      ["ex-step-up-with-knee-raise", "main", 3, 10],
      ["ex-dead-bug", "main", 3, 8],
      ["ex-hamstring-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- Desk Reset (free, 2 weeks, no equipment) --------------------------
  {
    id: "wk-desk-a",
    programId: "prog-desk-reset",
    name: "Morning Reset",
    order: 1,
    durationMinutes: 12,
    intensity: "beginner",
    exercises: [
      ["ex-arm-circles", "warmup", 1, 1],
      ["ex-cat-stretch", "main", 2, 1],
      ["ex-wrist-circles", "main", 2, 1],
      ["ex-hug-knees-to-chest", "main", 2, 1],
      ["ex-childs-pose", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-desk-b",
    programId: "prog-desk-reset",
    name: "Afternoon Reset",
    order: 2,
    durationMinutes: 12,
    intensity: "beginner",
    exercises: [
      ["ex-arm-circles", "warmup", 1, 1],
      ["ex-chair-squat", "main", 2, 12],
      ["ex-superman", "main", 2, 10],
      ["ex-hamstring-stretch", "main", 2, 1],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- Core & Stability (4 weeks) ----------------------------------------
  {
    id: "wk-core-a",
    programId: "prog-core-strength",
    name: "Core Day 1",
    order: 1,
    durationMinutes: 20,
    intensity: "beginner",
    exercises: [
      ["ex-jog", "warmup", 1, 1],
      ["ex-plank", "main", 3, 1],
      ["ex-dead-bug", "main", 3, 10],
      ["ex-russian-twist", "main", 3, 20],
      ["ex-crunch", "main", 3, 20],
      ["ex-superman", "main", 3, 12],
      ["ex-cat-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-core-b",
    programId: "prog-core-strength",
    name: "Core Day 2",
    order: 2,
    durationMinutes: 25,
    intensity: "intermediate",
    exercises: [
      ["ex-mountain-climber", "warmup", 1, 1],
      ["ex-leg-raise", "main", 3, 10],
      ["ex-side-plank", "main", 3, 1],
      ["ex-glute-bridge", "main", 3, 12],
      ["ex-plank", "main", 3, 1],
      ["ex-childs-pose", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-core-c",
    programId: "prog-core-strength",
    name: "Core Day 3: Anti-Rotation",
    order: 3,
    durationMinutes: 25,
    intensity: "intermediate",
    exercises: [
      ["ex-jump-rope", "warmup", 1, 1],
      ["ex-pallof-press", "main", 3, 12],
      ["ex-standing-cable-wood-chop", "main", 3, 12],
      ["ex-barbell-ab-rollout-on-knees", "main", 3, 8],
      ["ex-cable-crunch", "main", 3, 15],
      ["ex-hug-knees-to-chest", "cooldown", 1, 1],
    ],
  },

  // ---- Kettlebell Conditioning (5 weeks, one kettlebell) -----------------
  {
    id: "wk-kb-a",
    programId: "prog-kettlebell",
    name: "Kettlebell Day 1",
    order: 1,
    durationMinutes: 30,
    intensity: "intermediate",
    exercises: [
      ["ex-arm-circles", "warmup", 1, 1],
      ["ex-goblet-squat", "main", 4, 12],
      ["ex-two-arm-kettlebell-row", "main", 4, 10],
      ["ex-kettlebell-thruster", "main", 3, 10],
      ["ex-side-plank", "main", 3, 1],
      ["ex-worlds-greatest-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-kb-b",
    programId: "prog-kettlebell",
    name: "Kettlebell Day 2",
    order: 2,
    durationMinutes: 30,
    intensity: "intermediate",
    exercises: [
      ["ex-jump-rope", "warmup", 1, 1],
      ["ex-kettlebell-sumo-high-pull", "main", 4, 12],
      ["ex-goblet-squat", "main", 3, 15],
      ["ex-alternating-renegade-row", "main", 3, 10],
      ["ex-russian-twist", "main", 3, 20],
      ["ex-hamstring-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- HIIT Fat Burn (6 weeks) -------------------------------------------
  {
    id: "wk-hiit-a",
    programId: "prog-hiit-shred",
    name: "Circuit A: Full Body Burn",
    order: 1,
    durationMinutes: 25,
    intensity: "intermediate",
    exercises: [
      ["ex-jump-rope", "warmup", 1, 1],
      ["ex-jump-squat", "main", 4, 15],
      ["ex-mountain-climber", "main", 4, 20],
      ["ex-pushup", "main", 4, 12],
      ["ex-russian-twist", "main", 4, 20],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-hiit-b",
    programId: "prog-hiit-shred",
    name: "Circuit B: Conditioning",
    order: 2,
    durationMinutes: 30,
    intensity: "intermediate",
    exercises: [
      ["ex-rowing-machine", "warmup", 1, 1],
      ["ex-walking-lunge", "main", 4, 12],
      ["ex-bench-dip", "main", 4, 12],
      ["ex-mountain-climber", "main", 4, 20],
      ["ex-crunch", "main", 4, 20],
      ["ex-hamstring-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-hiit-c",
    programId: "prog-hiit-shred",
    name: "Circuit C: Power Intervals",
    order: 3,
    durationMinutes: 25,
    intensity: "advanced",
    exercises: [
      ["ex-jump-rope", "warmup", 1, 1],
      ["ex-bench-jump", "main", 4, 12],
      ["ex-plyo-push-up", "main", 4, 8],
      ["ex-kettlebell-thruster", "main", 4, 10],
      ["ex-scissor-kick", "main", 4, 20],
      ["ex-childs-pose", "cooldown", 1, 1],
    ],
  },

  // ---- Glute Builder (6 weeks) -------------------------------------------
  {
    id: "wk-glute-a",
    programId: "prog-glute-strength",
    name: "Glutes Day 1: Heavy Hinge",
    order: 1,
    durationMinutes: 45,
    intensity: "intermediate",
    exercises: [
      ["ex-stationary-bike", "warmup", 1, 1],
      ["ex-hip-thrust", "main", 4, 10],
      ["ex-romanian-deadlift", "main", 4, 10],
      ["ex-barbell-lunge", "main", 3, 10],
      ["ex-standing-barbell-calf-raise", "main", 3, 15],
      ["ex-hamstring-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-glute-b",
    programId: "prog-glute-strength",
    name: "Glutes Day 2: Volume",
    order: 2,
    durationMinutes: 40,
    intensity: "intermediate",
    exercises: [
      ["ex-monster-walk", "warmup", 1, 1],
      ["ex-barbell-glute-bridge", "main", 4, 12],
      ["ex-glute-kickback", "main", 3, 15],
      ["ex-one-legged-cable-kickback", "main", 3, 12],
      ["ex-thigh-abductor", "main", 3, 15],
      ["ex-side-lying-groin-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-glute-c",
    programId: "prog-glute-strength",
    name: "Glutes Day 3: Unilateral",
    order: 3,
    durationMinutes: 40,
    intensity: "intermediate",
    exercises: [
      ["ex-monster-walk", "warmup", 1, 1],
      ["ex-step-up-with-knee-raise", "main", 4, 10],
      ["ex-split-squat-with-dumbbells", "main", 3, 10],
      ["ex-glute-bridge", "main", 3, 12],
      ["ex-pull-through", "main", 3, 15],
      ["ex-worlds-greatest-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- Upper Body Sculpt (6 weeks) ---------------------------------------
  {
    id: "wk-ups-push",
    programId: "prog-upper-sculpt",
    name: "Upper Push",
    order: 1,
    durationMinutes: 45,
    intensity: "intermediate",
    exercises: [
      ["ex-band-pull-apart", "warmup", 1, 1],
      ["ex-bench-press", "main", 4, 10],
      ["ex-seated-dumbbell-press", "main", 4, 10],
      ["ex-dumbbell-flyes", "main", 3, 12],
      ["ex-lateral-raise", "main", 3, 15],
      ["ex-triceps-pushdown-rope-attachment", "main", 3, 12],
      ["ex-cat-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-ups-pull",
    programId: "prog-upper-sculpt",
    name: "Upper Pull",
    order: 2,
    durationMinutes: 45,
    intensity: "intermediate",
    exercises: [
      ["ex-band-pull-apart", "warmup", 1, 1],
      ["ex-close-grip-front-lat-pulldown", "main", 4, 10],
      ["ex-bent-over-two-dumbbell-row", "main", 4, 10],
      ["ex-reverse-flyes", "main", 3, 15],
      ["ex-ez-bar-curl", "main", 3, 12],
      ["ex-hammer-curl", "main", 3, 12],
      ["ex-childs-pose", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-ups-arms",
    programId: "prog-upper-sculpt",
    name: "Arms & Shoulders",
    order: 3,
    durationMinutes: 40,
    intensity: "intermediate",
    exercises: [
      ["ex-arm-circles", "warmup", 1, 1],
      ["ex-arnold-dumbbell-press", "main", 4, 10],
      ["ex-front-dumbbell-raise", "main", 3, 12],
      ["ex-preacher-curl", "main", 3, 12],
      ["ex-ez-bar-skullcrusher", "main", 3, 12],
      ["ex-barbell-shrug", "main", 3, 12],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- Progressive Strength (8 weeks) ------------------------------------
  {
    id: "wk-ps-upper",
    programId: "prog-strength-intermediate",
    name: "Week A: Upper Body",
    order: 1,
    durationMinutes: 50,
    intensity: "intermediate",
    exercises: [
      ["ex-jump-rope", "warmup", 1, 1],
      ["ex-bench-press", "main", 4, 8],
      ["ex-barbell-row", "main", 4, 8],
      ["ex-shoulder-press", "main", 3, 10],
      ["ex-lat-pulldown", "main", 3, 10],
      ["ex-triceps-pushdown", "main", 3, 12],
      ["ex-cat-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-ps-lower",
    programId: "prog-strength-intermediate",
    name: "Week A: Lower Body",
    order: 2,
    durationMinutes: 50,
    intensity: "intermediate",
    exercises: [
      ["ex-stationary-bike", "warmup", 1, 1],
      ["ex-barbell-squat", "main", 4, 6],
      ["ex-romanian-deadlift", "main", 4, 8],
      ["ex-leg-press", "main", 3, 10],
      ["ex-calf-raise", "main", 3, 15],
      ["ex-hamstring-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-ps-full",
    programId: "prog-strength-intermediate",
    name: "Week B: Full Body Power",
    order: 3,
    durationMinutes: 55,
    intensity: "advanced",
    exercises: [
      ["ex-jump-rope", "warmup", 1, 1],
      ["ex-deadlift", "main", 5, 5],
      ["ex-pullup", "main", 4, 6],
      ["ex-incline-press", "main", 3, 8],
      ["ex-hip-thrust", "main", 3, 10],
      ["ex-plank", "main", 3, 1],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- 5K to Half Marathon (10 weeks) ------------------------------------
  {
    id: "wk-run-easy",
    programId: "prog-run-5k-half",
    name: "Easy Run",
    order: 1,
    durationMinutes: 35,
    intensity: "beginner",
    exercises: [
      ["ex-arm-circles", "warmup", 1, 1],
      ["ex-treadmill-run", "main", 1, 1],
      ["ex-runners-stretch", "cooldown", 1, 1],
      ["ex-standing-gastrocnemius-calf-stretch", "cooldown", 2, 1],
    ],
  },
  {
    id: "wk-run-intervals",
    programId: "prog-run-5k-half",
    name: "Interval Session",
    order: 2,
    durationMinutes: 40,
    intensity: "advanced",
    exercises: [
      ["ex-jog", "warmup", 1, 1],
      ["ex-treadmill-run", "main", 8, 1],
      ["ex-hamstring-stretch", "cooldown", 2, 1],
      ["ex-runners-stretch", "cooldown", 2, 1],
    ],
  },
  {
    id: "wk-run-strength",
    programId: "prog-run-5k-half",
    name: "Runner's Strength",
    order: 3,
    durationMinutes: 35,
    intensity: "intermediate",
    exercises: [
      ["ex-monster-walk", "warmup", 1, 1],
      ["ex-walking-lunge", "main", 3, 12],
      ["ex-glute-bridge", "main", 3, 12],
      ["ex-standing-dumbbell-calf-raise", "main", 3, 15],
      ["ex-side-plank", "main", 3, 1],
      ["ex-worlds-greatest-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- Athletic Performance (combined, 8 weeks) --------------------------
  {
    id: "wk-ath-power",
    programId: "prog-athlete-performance",
    name: "Power Day",
    order: 1,
    durationMinutes: 50,
    intensity: "advanced",
    exercises: [
      ["ex-jump-rope", "warmup", 1, 1],
      ["ex-power-clean", "main", 5, 3],
      ["ex-front-squat-clean-grip", "main", 4, 5],
      ["ex-bench-jump", "main", 4, 6],
      ["ex-pallof-press", "main", 3, 12],
      ["ex-worlds-greatest-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-ath-speed",
    programId: "prog-athlete-performance",
    name: "Speed & Agility",
    order: 2,
    durationMinutes: 40,
    intensity: "advanced",
    exercises: [
      ["ex-jog", "warmup", 1, 1],
      ["ex-treadmill-run", "main", 6, 1],
      ["ex-jump-squat", "main", 4, 10],
      ["ex-mountain-climber", "main", 3, 20],
      ["ex-runners-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-ath-strength",
    programId: "prog-athlete-performance",
    name: "Strength Day",
    order: 3,
    durationMinutes: 55,
    intensity: "advanced",
    exercises: [
      ["ex-stationary-bike", "warmup", 1, 1],
      ["ex-barbell-full-squat", "main", 5, 5],
      ["ex-overhead-squat", "main", 3, 6],
      ["ex-barbell-row", "main", 4, 8],
      ["ex-good-morning", "main", 3, 10],
      ["ex-hamstring-stretch", "cooldown", 1, 1],
    ],
  },

  // ---- Powerlifting Foundations (10 weeks) -------------------------------
  {
    id: "wk-pl-squat",
    programId: "prog-powerlifting",
    name: "Squat Day",
    order: 1,
    durationMinutes: 60,
    intensity: "advanced",
    exercises: [
      ["ex-stationary-bike", "warmup", 1, 1],
      ["ex-barbell-full-squat", "main", 5, 5],
      ["ex-box-squat", "main", 3, 5],
      ["ex-leg-press", "main", 3, 10],
      ["ex-plank", "main", 3, 1],
      ["ex-hamstring-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-pl-bench",
    programId: "prog-powerlifting",
    name: "Bench Day",
    order: 2,
    durationMinutes: 55,
    intensity: "advanced",
    exercises: [
      ["ex-band-pull-apart", "warmup", 1, 1],
      ["ex-barbell-bench-press-medium-grip", "main", 5, 5],
      ["ex-close-grip-barbell-bench-press", "main", 3, 6],
      ["ex-barbell-row", "main", 4, 8],
      ["ex-seated-triceps-press", "main", 3, 10],
      ["ex-cat-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-pl-deadlift",
    programId: "prog-powerlifting",
    name: "Deadlift Day",
    order: 3,
    durationMinutes: 60,
    intensity: "advanced",
    exercises: [
      ["ex-stationary-bike", "warmup", 1, 1],
      ["ex-deadlift", "main", 5, 3],
      ["ex-rack-pulls", "main", 3, 5],
      ["ex-good-morning", "main", 3, 8],
      ["ex-hyperextensions-with-no-hyperextension-bench", "main", 3, 12],
      ["ex-hug-knees-to-chest", "cooldown", 1, 1],
    ],
  },

  // ---- Lean Muscle Builder (combined, 12 weeks) --------------------------
  {
    id: "wk-lm-push",
    programId: "prog-lean-muscle",
    name: "Push Day",
    order: 1,
    durationMinutes: 55,
    intensity: "intermediate",
    exercises: [
      ["ex-jog", "warmup", 1, 1],
      ["ex-bench-press", "main", 4, 10],
      ["ex-incline-press", "main", 4, 10],
      ["ex-shoulder-press", "main", 3, 10],
      ["ex-lateral-raise", "main", 3, 12],
      ["ex-triceps-pushdown", "main", 3, 12],
      ["ex-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-lm-pull",
    programId: "prog-lean-muscle",
    name: "Pull Day",
    order: 2,
    durationMinutes: 55,
    intensity: "intermediate",
    exercises: [
      ["ex-jog", "warmup", 1, 1],
      ["ex-lat-pulldown", "main", 4, 10],
      ["ex-seated-row", "main", 4, 10],
      ["ex-barbell-row", "main", 3, 8],
      ["ex-face-pull", "main", 3, 15],
      ["ex-hammer-curl", "main", 3, 12],
      ["ex-bicep-curl", "main", 3, 12],
      ["ex-cat-stretch", "cooldown", 1, 1],
    ],
  },
  {
    id: "wk-lm-legs",
    programId: "prog-lean-muscle",
    name: "Leg Day",
    order: 3,
    durationMinutes: 60,
    intensity: "intermediate",
    exercises: [
      ["ex-stationary-bike", "warmup", 1, 1],
      ["ex-barbell-squat", "main", 4, 8],
      ["ex-romanian-deadlift", "main", 4, 10],
      ["ex-hip-thrust", "main", 3, 12],
      ["ex-calf-raise", "main", 4, 15],
      ["ex-leg-raise", "main", 3, 10],
      ["ex-hamstring-stretch", "cooldown", 1, 1],
    ],
  },
];
